<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DestinationSeeder extends Seeder
{
    public function run(): void
    {
        if (DB::table('destinations')->count() > 0) {
            return;
        }

        DB::table('destinations')->insert([
            [
                'province_id' => 1,
                'municipality_id' => 1,
                'name' => 'Taal Heritage Town',
                'slug' => 'taal-heritage-town',
                'category_id' => 3,
                'short_description' => 'Historic houses and basilica',
                'description' => 'Explore preserved ancestral homes and church architecture in Taal, Batangas.',
                'price_label' => 'budget',
                'is_featured' => 1,
                'is_active' => 1,
                'is_verified' => 1,
                'avg_duration_hours' => 4,
                'avg_rating' => 4.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 1,
                'municipality_id' => 5,
                'name' => 'Anilao Dive Sites',
                'slug' => 'anilao-dive-sites',
                'category_id' => 2,
                'short_description' => 'World-class diving in Batangas',
                'description' => 'Coral reefs and marine biodiversity perfect for snorkeling and diving.',
                'price_label' => 'mid_range',
                'is_featured' => 1,
                'is_active' => 1,
                'is_verified' => 1,
                'avg_duration_hours' => 6,
                'avg_rating' => 4.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 2,
                'municipality_id' => 10,
                'name' => 'Pagsanjan Falls',
                'slug' => 'pagsanjan-falls',
                'category_id' => 1,
                'short_description' => 'Iconic river gorge adventure',
                'description' => 'Boat ride through rapids to reach the famous falls in Laguna.',
                'price_label' => 'budget',
                'is_featured' => 1,
                'is_active' => 1,
                'is_verified' => 1,
                'avg_duration_hours' => 5,
                'avg_rating' => 4.7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 2,
                'municipality_id' => 12,
                'name' => 'Mount Makiling Trail',
                'slug' => 'mount-makiling-trail',
                'category_id' => 5,
                'short_description' => 'Forest trek near Los Banos',
                'description' => 'Day hike with rich biodiversity and scenic viewpoints.',
                'price_label' => 'free',
                'is_featured' => 0,
                'is_active' => 1,
                'is_verified' => 1,
                'avg_duration_hours' => 7,
                'avg_rating' => 4.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 3,
                'municipality_id' => 16,
                'name' => 'Tagaytay Ridge View',
                'slug' => 'tagaytay-ridge-view',
                'category_id' => 1,
                'short_description' => 'Cool climate with volcano views',
                'description' => 'Panoramic views of Taal Volcano and food spots along Tagaytay ridge.',
                'price_label' => 'budget',
                'is_featured' => 1,
                'is_active' => 1,
                'is_verified' => 1,
                'avg_duration_hours' => 4,
                'avg_rating' => 4.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 3,
                'municipality_id' => 17,
                'name' => 'Puerto Azul Coast',
                'slug' => 'puerto-azul-coast',
                'category_id' => 2,
                'short_description' => 'Coastal getaway in Cavite',
                'description' => 'Beachfront relaxation and sunset views in Ternate.',
                'price_label' => 'mid_range',
                'is_featured' => 0,
                'is_active' => 1,
                'is_verified' => 1,
                'avg_duration_hours' => 6,
                'avg_rating' => 4.2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 4,
                'municipality_id' => 20,
                'name' => 'Pinto Art Museum',
                'slug' => 'pinto-art-museum',
                'category_id' => 3,
                'short_description' => 'Art and gardens in Antipolo',
                'description' => 'Contemporary art galleries and landscaped gardens.',
                'price_label' => 'budget',
                'is_featured' => 1,
                'is_active' => 1,
                'is_verified' => 1,
                'avg_duration_hours' => 3,
                'avg_rating' => 4.7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 4,
                'municipality_id' => 21,
                'name' => 'Daranak Falls',
                'slug' => 'daranak-falls',
                'category_id' => 1,
                'short_description' => 'Popular waterfall in Tanay',
                'description' => 'Swimming and picnic area surrounded by greenery.',
                'price_label' => 'budget',
                'is_featured' => 1,
                'is_active' => 1,
                'is_verified' => 1,
                'avg_duration_hours' => 5,
                'avg_rating' => 4.4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 5,
                'municipality_id' => 25,
                'name' => 'Kamay ni Hesus Shrine',
                'slug' => 'kamay-ni-hesus-shrine',
                'category_id' => 3,
                'short_description' => 'Pilgrimage site in Lucban area',
                'description' => 'Religious destination with scenic hillside views.',
                'price_label' => 'free',
                'is_featured' => 0,
                'is_active' => 1,
                'is_verified' => 1,
                'avg_duration_hours' => 3,
                'avg_rating' => 4.3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 5,
                'municipality_id' => 28,
                'name' => 'Quezon Eco Park',
                'slug' => 'quezon-eco-park',
                'category_id' => 1,
                'short_description' => 'Nature and leisure in Quezon',
                'description' => 'Family-friendly outdoor activities with forest trails.',
                'price_label' => 'budget',
                'is_featured' => 0,
                'is_active' => 1,
                'is_verified' => 1,
                'avg_duration_hours' => 4,
                'avg_rating' => 4.1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
